version: '3.5'

services:
  homebusinessdb:
    container_name: "homebusinessdb"
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: home_business
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres